name = "candy-shop"
compatibility_date = "2024-10-17"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Pages configuration
pages_build_output_dir = "dist"

# Functions configuration
[functions]
# External dependencies that should not be bundled
external_modules = ["stripe"]

# Environment variables (these will be set in Cloudflare dashboard)
[vars]
# Add any non-secret environment variables here

# Production environment
[env.production]
[env.production.vars]

# Development environment  
[env.development]
[env.development.vars]